from scripts.createsuperuser import createsuperuser
from scripts.startserver import startserver
from scripts.flushexpiredtokens import flushexpiredtokens
from scripts.loadgenshindata import loadgenshindata