"""add artifact

Revision ID: 1f8b4c31b278
Revises: a48260077fe2
Create Date: 2022-04-07 14:48:15.689590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f8b4c31b278'
down_revision = 'a48260077fe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifact_main_stat_cores',
    sa.Column('stat', sa.String(length=10), nullable=False),
    sa.Column('start_value', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifact_sub_stat_cores',
    sa.Column('stat', sa.String(length=10), nullable=False),
    sa.Column('start_value', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifact_cores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rarity', sa.SmallInteger(), nullable=False),
    sa.Column('artifact_type', sa.String(length=5), nullable=False),
    sa.Column('main_stat_core', sa.Integer(), nullable=False),
    sa.Column('first_sub_stat_core', sa.Integer(), nullable=True),
    sa.Column('second_sub_stat_core', sa.Integer(), nullable=True),
    sa.Column('third_sub_stat_core', sa.Integer(), nullable=True),
    sa.Column('fourth_sub_stat_core', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['first_sub_stat_core'], ['artifact_sub_stat_cores.id'], name='fk_artifact_cores_artifact_sub_stat_cores_id_first_sub_stat_core'),
    sa.ForeignKeyConstraint(['fourth_sub_stat_core'], ['artifact_sub_stat_cores.id'], name='fk_artifact_cores_artifact_sub_stat_cores_id_fourth_sub_stat_core'),
    sa.ForeignKeyConstraint(['main_stat_core'], ['artifact_main_stat_cores.id'], name='fk_artifact_cores_artifact_main_stat_cores_id_main_stat_core'),
    sa.ForeignKeyConstraint(['second_sub_stat_core'], ['artifact_sub_stat_cores.id'], name='fk_artifact_cores_artifact_sub_stat_cores_id_second_sub_stat_core'),
    sa.ForeignKeyConstraint(['third_sub_stat_core'], ['artifact_sub_stat_cores.id'], name='fk_artifact_cores_artifact_sub_stat_cores_id_third_sub_stat_core'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifact_main_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('core', sa.Integer(), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['core'], ['artifact_main_stat_cores.id'], name='fk_artifact_main_stats_artifact_main_stat_cores_id_core'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifact_sub_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('core', sa.Integer(), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['core'], ['artifact_sub_stat_cores.id'], name='fk_artifact_sub_stats_artifact_sub_stat_cores_id_core'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('core', sa.Integer(), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.Column('main_stat', sa.Integer(), nullable=False),
    sa.Column('first_sub_stat', sa.Integer(), nullable=True),
    sa.Column('second_sub_stat', sa.Integer(), nullable=True),
    sa.Column('third_sub_stat', sa.Integer(), nullable=True),
    sa.Column('fourth_sub_stat', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['core'], ['artifact_cores.id'], name='fk_artifacts_artifact_cores_id_core'),
    sa.ForeignKeyConstraint(['first_sub_stat'], ['artifact_sub_stats.id'], name='fk_artifacts_artifact_sub_stats_id_first_sub_stat'),
    sa.ForeignKeyConstraint(['fourth_sub_stat'], ['artifact_sub_stats.id'], name='fk_artifacts_artifact_sub_stats_id_fourth_sub_stat'),
    sa.ForeignKeyConstraint(['main_stat'], ['artifact_main_stat_cores.id'], name='fk_artifacts_artifact_main_stat_cores_id_main_stat'),
    sa.ForeignKeyConstraint(['second_sub_stat'], ['artifact_sub_stats.id'], name='fk_artifacts_artifact_sub_stats_id_second_sub_stat'),
    sa.ForeignKeyConstraint(['third_sub_stat'], ['artifact_sub_stats.id'], name='fk_artifacts_artifact_sub_stats_id_third_sub_stat'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artifacts')
    op.drop_table('artifact_sub_stats')
    op.drop_table('artifact_main_stats')
    op.drop_table('artifact_cores')
    op.drop_table('artifact_sub_stat_cores')
    op.drop_table('artifact_main_stat_cores')
    # ### end Alembic commands ###
