"""add artifact

Revision ID: 2f784d3def44
Revises: a48260077fe2
Create Date: 2022-04-16 12:20:20.313318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f784d3def44'
down_revision = 'a48260077fe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifact_main_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rarity', sa.SmallInteger(), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.Column('stat', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifact_set_bonuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stat', sa.String(length=10), nullable=False),
    sa.Column('stat_type', sa.String(length=5), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifact_sub_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rarity', sa.SmallInteger(), nullable=False),
    sa.Column('stat', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifact_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('max_rarity', sa.SmallInteger(), nullable=False),
    sa.Column('two_piece_bonus', sa.Integer(), nullable=False),
    sa.Column('four_piece_bonus', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['four_piece_bonus'], ['artifact_set_bonuses.id'], name='fk_artifact_sets_artifact_set_bonuses_id_four_piece_bonus'),
    sa.ForeignKeyConstraint(['two_piece_bonus'], ['artifact_set_bonuses.id'], name='fk_artifact_sets_artifact_set_bonuses_id_two_piece_bonus'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifact_cores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('artifact_set', sa.Integer(), nullable=False),
    sa.Column('artifact_type', sa.String(length=5), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['artifact_set'], ['artifact_sets.id'], name='fk_artifact_cores_artifact_sets_id_artifact_set'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('core', sa.Integer(), nullable=False),
    sa.Column('rarity', sa.SmallInteger(), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.Column('main_stat', sa.Integer(), nullable=False),
    sa.Column('first_sub_stat', sa.Integer(), nullable=True),
    sa.Column('second_sub_stat', sa.Integer(), nullable=True),
    sa.Column('third_sub_stat', sa.Integer(), nullable=True),
    sa.Column('fourth_sub_stat', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['core'], ['artifact_cores.id'], name='fk_artifacts_artifact_cores_id_core'),
    sa.ForeignKeyConstraint(['first_sub_stat'], ['artifact_sub_stats.id'], name='fk_artifacts_artifact_sub_stats_id_first_sub_stat'),
    sa.ForeignKeyConstraint(['fourth_sub_stat'], ['artifact_sub_stats.id'], name='fk_artifacts_artifact_sub_stats_id_fourth_sub_stat'),
    sa.ForeignKeyConstraint(['main_stat'], ['artifact_main_stats.id'], name='fk_artifacts_artifact_main_stats_id_main_stat'),
    sa.ForeignKeyConstraint(['second_sub_stat'], ['artifact_sub_stats.id'], name='fk_artifacts_artifact_sub_stats_id_second_sub_stat'),
    sa.ForeignKeyConstraint(['third_sub_stat'], ['artifact_sub_stats.id'], name='fk_artifacts_artifact_sub_stats_id_third_sub_stat'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artifacts')
    op.drop_table('artifact_cores')
    op.drop_table('artifact_sets')
    op.drop_table('artifact_sub_stats')
    op.drop_table('artifact_set_bonuses')
    op.drop_table('artifact_main_stats')
    # ### end Alembic commands ###
