"""add artifact and character

Revision ID: 8b4f08f52053
Revises: a48260077fe2
Create Date: 2022-04-24 11:33:41.715454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b4f08f52053'
down_revision = 'a48260077fe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifact_main_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rarity', sa.SmallInteger(), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.Column('stat', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifact_set_bonuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stat', sa.String(length=10), nullable=False),
    sa.Column('stat_type', sa.String(length=5), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifact_sub_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rarity', sa.SmallInteger(), nullable=False),
    sa.Column('stat', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('roll', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_ascensions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ascension', sa.SmallInteger(), nullable=False),
    sa.Column('sum_of_sections', sa.SmallInteger(), nullable=True),
    sa.Column('bonus_stat_multiplier', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_bonus_stat_cores',
    sa.Column('stat', sa.String(length=10), nullable=False),
    sa.Column('start_value', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_level_multipliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.Column('rarity', sa.SmallInteger(), nullable=False),
    sa.Column('multiplier', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifact_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('max_rarity', sa.SmallInteger(), nullable=False),
    sa.Column('two_piece_bonus', sa.Integer(), nullable=False),
    sa.Column('four_piece_bonus', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['four_piece_bonus'], ['artifact_set_bonuses.id'], name='fk_artifact_sets_artifact_set_bonuses_id_four_piece_bonus'),
    sa.ForeignKeyConstraint(['two_piece_bonus'], ['artifact_set_bonuses.id'], name='fk_artifact_sets_artifact_set_bonuses_id_two_piece_bonus'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_bonus_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('core', sa.Integer(), nullable=False),
    sa.Column('ascension', sa.SmallInteger(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['core'], ['character_bonus_stat_cores.id'], name='fk_character_bonus_stats_character_bonus_stat_cores_id_core'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_cores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rarity', sa.SmallInteger(), nullable=False),
    sa.Column('health_start_value', sa.Float(), nullable=False),
    sa.Column('attack_start_value', sa.Float(), nullable=False),
    sa.Column('deffence_start_value', sa.Float(), nullable=False),
    sa.Column('crit_rate_start_value', sa.Float(), nullable=True),
    sa.Column('crit_damage_start_value', sa.Float(), nullable=True),
    sa.Column('bonus_stat_core', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('max_ascension_health', sa.Float(), nullable=False),
    sa.Column('max_ascension_attack', sa.Float(), nullable=False),
    sa.Column('max_ascension_deffence', sa.Float(), nullable=False),
    sa.Column('element', sa.String(length=1), nullable=False),
    sa.Column('weapon_type', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['bonus_stat_core'], ['character_bonus_stat_cores.id'], name='fk_character_cores_character_bonus_stat_cores_id_bonus_stat_core'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifact_cores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('artifact_set', sa.Integer(), nullable=False),
    sa.Column('artifact_type', sa.String(length=7), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['artifact_set'], ['artifact_sets.id'], name='fk_artifact_cores_artifact_sets_id_artifact_set'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('core', sa.Integer(), nullable=False),
    sa.Column('rarity', sa.SmallInteger(), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.Column('main_stat', sa.Integer(), nullable=False),
    sa.Column('first_sub_stat', sa.Integer(), nullable=True),
    sa.Column('second_sub_stat', sa.Integer(), nullable=True),
    sa.Column('third_sub_stat', sa.Integer(), nullable=True),
    sa.Column('fourth_sub_stat', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['core'], ['artifact_cores.id'], name='fk_artifacts_artifact_cores_id_core'),
    sa.ForeignKeyConstraint(['first_sub_stat'], ['artifact_sub_stats.id'], name='fk_artifacts_artifact_sub_stats_id_first_sub_stat'),
    sa.ForeignKeyConstraint(['fourth_sub_stat'], ['artifact_sub_stats.id'], name='fk_artifacts_artifact_sub_stats_id_fourth_sub_stat'),
    sa.ForeignKeyConstraint(['main_stat'], ['artifact_main_stats.id'], name='fk_artifacts_artifact_main_stats_id_main_stat'),
    sa.ForeignKeyConstraint(['second_sub_stat'], ['artifact_sub_stats.id'], name='fk_artifacts_artifact_sub_stats_id_second_sub_stat'),
    sa.ForeignKeyConstraint(['third_sub_stat'], ['artifact_sub_stats.id'], name='fk_artifacts_artifact_sub_stats_id_third_sub_stat'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_core', sa.Integer(), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.Column('ascension', sa.SmallInteger(), nullable=False),
    sa.Column('health', sa.Float(), nullable=False),
    sa.Column('attack', sa.Float(), nullable=False),
    sa.Column('deffence', sa.Float(), nullable=False),
    sa.Column('crit_rate', sa.Float(), nullable=False),
    sa.Column('crit_damage', sa.Float(), nullable=False),
    sa.Column('elemental_mastery', sa.Float(), nullable=True),
    sa.Column('energy_recharge', sa.Float(), nullable=True),
    sa.Column('healing_bonus', sa.Float(), nullable=True),
    sa.Column('bonus_stat', sa.Integer(), nullable=False),
    sa.Column('weapon', sa.Integer(), nullable=False),
    sa.Column('phys_damage_bonus', sa.Float(), nullable=True),
    sa.Column('anemo_damage_bonus', sa.Float(), nullable=True),
    sa.Column('geo_damage_bonus', sa.Float(), nullable=True),
    sa.Column('electro_damage_bonus', sa.Float(), nullable=True),
    sa.Column('hydro_damage_bonus', sa.Float(), nullable=True),
    sa.Column('pyro_damage_bonus', sa.Float(), nullable=True),
    sa.Column('cryo_damage_bonus', sa.Float(), nullable=True),
    sa.Column('phys_damage_resistance', sa.Float(), nullable=True),
    sa.Column('anemo_damage_resistance', sa.Float(), nullable=True),
    sa.Column('geo_damage_resistance', sa.Float(), nullable=True),
    sa.Column('electro_damage_resistance', sa.Float(), nullable=True),
    sa.Column('hydro_damage_resistance', sa.Float(), nullable=True),
    sa.Column('pyro_damage_resistance', sa.Float(), nullable=True),
    sa.Column('cryo_damage_resistance', sa.Float(), nullable=True),
    sa.Column('stamina', sa.Float(), nullable=True),
    sa.Column('cd_reduction', sa.Float(), nullable=True),
    sa.Column('incoming_healing_bonus', sa.Float(), nullable=True),
    sa.Column('shield_strength', sa.Float(), nullable=True),
    sa.Column('artifact_flower', sa.Integer(), nullable=True),
    sa.Column('artifact_plume', sa.Integer(), nullable=True),
    sa.Column('artifact_sands', sa.Integer(), nullable=True),
    sa.Column('artifact_goblet', sa.Integer(), nullable=True),
    sa.Column('artifact_circlet', sa.Integer(), nullable=True),
    sa.Column('total_attack', sa.Float(), nullable=False),
    sa.Column('total_health', sa.Float(), nullable=False),
    sa.Column('total_deffence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_circlet'], ['artifacts.id'], name='fk_characters_artifacts_id_artifact_circlet'),
    sa.ForeignKeyConstraint(['artifact_flower'], ['artifacts.id'], name='fk_characters_artifacts_id_artifact_flower'),
    sa.ForeignKeyConstraint(['artifact_goblet'], ['artifacts.id'], name='fk_characters_artifacts_id_artifact_goblet'),
    sa.ForeignKeyConstraint(['artifact_plume'], ['artifacts.id'], name='fk_characters_artifacts_id_artifact_plume'),
    sa.ForeignKeyConstraint(['artifact_sands'], ['artifacts.id'], name='fk_characters_artifacts_id_artifact_sands'),
    sa.ForeignKeyConstraint(['bonus_stat'], ['character_bonus_stats.id'], name='fk_characters_character_bonus_stats_id_bonus_stat'),
    sa.ForeignKeyConstraint(['character_core'], ['character_cores.id'], name='fk_characters_character_cores_id_character_core'),
    sa.ForeignKeyConstraint(['weapon'], ['weapons.id'], name='fk_characters_weapons_id_weapon'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('characters')
    op.drop_table('artifacts')
    op.drop_table('artifact_cores')
    op.drop_table('character_cores')
    op.drop_table('character_bonus_stats')
    op.drop_table('artifact_sets')
    op.drop_table('character_level_multipliers')
    op.drop_table('character_bonus_stat_cores')
    op.drop_table('character_ascensions')
    op.drop_table('artifact_sub_stats')
    op.drop_table('artifact_set_bonuses')
    op.drop_table('artifact_main_stats')
    # ### end Alembic commands ###
